server:
  port: 8765
spring:
  application:
    name: edge-service
eureka:
  client:
    fetch-registry: true
zuul:
  routes:
    gabbles-service:
      path: /gabbles
      url: http://localhost:8080
    home:
      path: /home
      url: http://localhost:8080
  sensitive-headers: Cookie,Set-Cookie
security:
  oauth2:
    client:
      client-id: 0oah02ykwu2GWXRcU0h7
      client-secret: SCDMxLe4Dl04PkGwGj-OZTbn7OyqC7rR47JFinrU
      access-token-uri: https://dev-934296.oktapreview.com/oauth2/default/v1/token
      user-authorization-uri: https://dev-934296.oktapreview.com/oauth2/default/v1/authorize
      scope: openid profile email
    resource:
      user-info-uri: https://dev-934296.oktapreview.com/oauth2/default/v1/userinfo
feign:
  hystrix:
    enabled: true
hystrix:
  shareSecurityContext: true