spring:
  jpa:
    show-sql: true
  application:
    name: user-profiles-service
server:
  port: 8090

---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/gabble_user_profiles
    username: aPzhffHaiCRmKquRGmLXivCetTBiPukt
    password: 7Lm3RzoGOFAxZjKOXgLOpNssUYCCCLMIerXbVU7cLw8OU07AyJnQUfqMdx4RS3KL
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
