spring:
  application:
    name: netflix-zuul-api-gateway-server
server:
  port: 8765
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
zuul:
  routes:
    auth-service:
      # Map path to auth service
      path: /auth/**
      service-id: AUTH-SERVICE
      # By default, all requests to gallery service for example will start with: "/gallery/"
      # What will be sent to the gallery service is what comes after the path defined,
      # So, if request is "/gallery/view/1", gallery service will get "/view/1".
      # In case of auth, we need to pass the "/auth/" in the path to auth service. So, set strip-prefix to false
      strip-prefix: false
      # Exclude authorization from sensitive headers
      sensitive-headers: Cookie,Set-Cookie