spring:
  application:
    name: spring-cloud-config-server

  cloud:
    config:
      server:
        git:
          uri: file:///Users/johanvergeer/projects/udemy-spring-cloud/spring-cloud-config-server/git-localconfig-repo
server:
  port: 8888